version: '3'
services:
  # db:
  #   image: postgres
  #   container_name: CI_CD_server_postgres
  #   environment:
  #     # POSTGRES_HOST_AUTH_METHOD: trust
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: test
  #   ports:
  #     - 5432:5432
  #   restart: always
  web:
    build: .
    container_name: CI_CD_server_flask
    ports:
      - '5000:5000'
    # depends_on:
    #   - db
    # restart: always
